# Generated by Django 4.2.7 on 2023-11-02 23:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Knight', 'Knight'), ('Thief', 'Thief'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Ranger', 'Ranger'), ('Paladin', 'Paladin'), ('Barbarian', 'Barbarian'), ('Druid', 'Druid'), ('Bard', 'Bard'), ('Monk', 'Monk'), ('Necromancer', 'Necromancer')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Orc', 'Orc'), ('Halfling', 'Halfling'), ('Centaur', 'Centaur'), ('Half-elf', 'Half-Elf'), ('Half-orc', 'Half-Orc'), ('Minotaur', 'Minotaur'), ('Lizardfolk', 'Lizardfolk'), ('Dragonborn', 'Dragonborn'), ('Sylvari', 'Sylvari')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('hp', models.PositiveIntegerField(default=200)),
                ('damage', models.PositiveIntegerField(default=20)),
                ('strength', models.PositiveIntegerField(default=20)),
                ('intelligence', models.PositiveIntegerField(default=20)),
                ('constitution', models.PositiveIntegerField(default=20)),
                ('dexterity', models.PositiveIntegerField(default=20)),
                ('luck', models.PositiveIntegerField(default=20)),
                ('wisdom', models.PositiveIntegerField(default=20)),
                ('skill_points', models.PositiveIntegerField(default=0)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('physical_res', models.PositiveIntegerField(default=20)),
                ('magic_res', models.PositiveIntegerField(default=20)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('collected_gold', models.PositiveIntegerField(default=0)),
                ('killed_monsters', models.PositiveIntegerField(default=0)),
                ('killed_players', models.PositiveIntegerField(default=0)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.characterclass')),
                ('character_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.characterrace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
