# Generated by Django 4.2.7 on 2023-11-02 23:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('item_type', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('hp', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('rarity', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('physical_res', models.PositiveIntegerField(default=0)),
                ('magic_res', models.PositiveIntegerField(default=0)),
                ('enhancement_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('enhancement_cost', models.IntegerField(default=0)),
                ('shop_type', models.CharField(blank=True, max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
